name: Add bugs and PRs to the Release Smoothie GitHub Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/7
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT || github.token }}
          label-operator: AND
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/4 # Add issue to the packaging project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT || github.token }}
          labeled: packaging
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/25 # Add issue to the documentation project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: documentation
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/5 # Add issue to the folksonomy project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: folksonomy project
          label-operator: OR   
